resources:
  - statefulset.yaml
  - services.yaml

configMapGenerator:
  - name: mysql-config-files
    files:
      - node.cnf
  - name: mysql-startup-scripts
    files:
      - entrypoint.sh
      - functions.sh
  - name: mysql
    literals:
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=default
      - ALLOW_ROOT_FROM='%'
      - PXC_STRICT_MODE=ENFORCING
      - DEBUG="true"

secretGenerator:
  - name: mysql
    literals:
      - MYSQL_PASSWORD=oyMxgZChuu
      - MYSQL_ROOT_PASSWORD=2dMJTrx8y9
      - XTRABACKUP_PASSWORD=4WHuZ4xTLq
