resources:
  - statefulset.yaml
  - secret.yaml
  - services.yaml

configMapGenerator:
  - name: mysql-config-files
    files:
      - node.cnf
  - name: mysql-startup-scripts
    files:
      - entrypoint.sh
      - functions.sh
