# Note that all references to mysql here are to `centralledger-mysql`. Hypothetically, kustomize
# should allow us to use just `mysql` as when this kustomization is being built the mysql
# dependency is the only possible name for `mysql`.. However, it looks like these names are
# resolved globally, rather than hierarchically, which means we must use `centralledger-mysql`
# instead of `mysql`. Which means whenever we rename our centralledger mysql instance, we must
# replace all instances of `centralledger-mysql` with the new name.
commonLabels:
  app.kubernetes.io/part-of: mojaloop
resources:
# consider attempting to replace kafka with Redpanda
- ../../kafka
- ./centralledger-mysql
- ../../centralledger

configMapGenerator:
- name: centralledger-mysql
  behavior: merge
  literals:
  - MYSQL_DATABASE=central_ledger
  - MYSQL_USER=central_ledger

secretGenerator:
- name: centralledger-mysql
  behavior: merge
  literals:
  - MYSQL_PASSWORD=oyMxgZChuu
  - MYSQL_ROOT_PASSWORD=2dMJTrx8y9
  - XTRABACKUP_PASSWORD=4WHuZ4xTLq

patches:
- target:
    kind: Deployment
    name: centralledger-handler-.*
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored-by-kustomize
    spec:
      template:
        spec:
          # TODO: apply wait-for-mysql and wait-for-kafka to all relevant images with a patch as
          #       follows. This also means removing them from the bases. Additionally, use the
          #       relevant MySQL and Kafka configmaps.
          initContainers:
          - name: wait-for-mysql
            command:
            - sh
            - -c
            - until result=$(mysql -h "$MYSQL_SERVICE" -P 3306 -u "$MYSQL_USER"
              --password="$MYSQL_PASSWORD"  "$MYSQL_DATABASE" -ss -N -e 'select is_locked from
              migration_lock;') && eval 'echo is_locked=$result' && if [ -z $result
              ]; then false; fi && if [ $result -ne 0 ]; then false; fi; do echo waiting
              for MySQL; sleep 2; done;
            image: mysql:latest
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: centralledger-mysql
            - secretRef:
                name: centralledger-mysql
          - command:
            - sh
            - -c
            # TODO: parametrise the Kafka service and port
            - until ./bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092;
              do
                echo waiting for Kafka;
                sleep 2;
              done;
            image: solsson/kafka:latest
            imagePullPolicy: Always
            name: wait-for-kafka
