# Note that all references to mysql here are to `centralledger-mysql`. Hypothetically, kustomize
# should allow us to use just `mysql` as when this kustomization is being built the mysql
# dependency is the only possible name for `mysql`.. However, it looks like these names are
# resolved globally, rather than hierarchically, which means we must use `centralledger-mysql`
# instead of `mysql`. Which means whenever we rename our centralledger mysql instance, we must
# replace all instances of `centralledger-mysql` with the new name.
commonLabels:
  app.kubernetes.io/part-of: mojaloop
resources:
- ../../kafka
- ./centralledger-mysql
- ../../centralledger

configMapGenerator:
- name: centralledger-mysql
  behavior: merge
  literals:
  - MYSQL_DATABASE=central_ledger
  - MYSQL_USER=central_ledger

secretGenerator:
- name: centralledger-mysql
  behavior: merge
  literals:
  - MYSQL_PASSWORD=oyMxgZChuu
  - MYSQL_ROOT_PASSWORD=2dMJTrx8y9
  - XTRABACKUP_PASSWORD=4WHuZ4xTLq
