apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: mojaloop-kustomize
deploy:
  kustomize:
    paths:
    - base/mojaloop
profiles:
- name: minikube-integration
  deploy:
    kustomize:
      paths:
      - base/insecure-minikube-integration-test
- name: mysql
  deploy:
    kustomize:
      paths:
      - base/mysql
