apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralledger-handler
  labels:
    app.kubernetes.io/name: centralledger-handler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: centralledger-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: centralledger-handler
    spec:
      containers:
      - command:
        - node
        - src/handlers/index.js
        - handler
        - --handler # This will fail. We don't want it to succeed- this should be overridden in overlays.
        env:
        - name: CLEDG_HOSTNAME
          value: centralledger-handler
        - name: CLEDG_INSTRUMENTATION__METRICS__config__defaultLabels__serviceName
          value: centralledger-handler
        - name: LOG_LEVEL
          value: info
        - name: LOG_FILTER
          value: error, warn, info
        - name: CSL_LOG_TRANSPORT
          value: console
        - name: EVENT_SDK_SIDECAR_DISABLED
          value: "true"
        image: mojaloop/central-ledger:v11.2.3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
        name: handler
        ports:
        - containerPort: 3001
          name: http-api
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
      restartPolicy: Always
