apiVersion: v1
data:
  default.json: "\n{\n  \"HOSTNAME\": \"http://quoting-service.local\",\n  \"LISTEN_ADDRESS\"\
    : \"0.0.0.0\",\n  \"PORT\": 3002,\n  \"SWITCH_ENDPOINT\": \"http://centralledger-service:80\"\
    ,\n  \"AMOUNT\": {\n    \"PRECISION\": 18,\n    \"SCALE\": 4\n  },\n  \"ERROR_HANDLING\"\
    : {\n    \"includeCauseExtension\": false,\n    \"truncateExtensions\": true\n\
    \  },\n  \"DATABASE\": {\n    \"DIALECT\": \"mysql\",\n    \"HOST\": \"mysql\"\
    ,\n    \"PORT\": 3306,\n    \"USER\": \"central_ledger\",\n    \"PASSWORD\": \"\
    oyMxgZChuu\",\n    \"SCHEMA\": \"central_ledger\",\n    \"POOL_MIN_SIZE\": 10,\n\
    \    \"POOL_MAX_SIZE\": 30,\n    \"ACQUIRE_TIMEOUT_MILLIS\": 30000,\n    \"CREATE_TIMEOUT_MILLIS\"\
    : 30000,\n    \"DESTROY_TIMEOUT_MILLIS\": 5000,\n    \"IDLE_TIMEOUT_MILLIS\":\
    \ 30000,\n    \"REAP_INTERVAL_MILLIS\": 1000,\n    \"CREATE_RETRY_INTERVAL_MILLIS\"\
    : 200,\n    \"DEBUG\": false\n  },\n  \"SIMPLE_ROUTING_MODE\": true\n}\n"
  rules.json: '[]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: quoting-service
  name: quoting-service-config
---
apiVersion: v1
data:
  default.json: "{\n  \"PORT\": 4001,\n  \"EVENT_LOGGER_GRPC_HOST\": \"localhost\"\
    ,\n  \"EVENT_LOGGER_GRPC_PORT\": 50051,\n  \"INSTRUMENTATION\": {\n    \"METRICS\"\
    : {\n      \"DISABLED\": false,\n      \"labels\": {\n        \"eventId\": \"\
    *\"\n      },\n      \"config\": {\n        \"timeout\": 5000,\n        \"prefix\"\
    : \"moja_\",\n        \"defaultLabels\": {\n          \"serviceName\": \"quoting-service-event-sidecar\"\
    \n        }\n      }\n    }\n  },\n  \"KAFKA\": {\n    \"TOPIC_TEMPLATES\": {\n\
    \      \"GENERAL_TOPIC_TEMPLATE\": {\n        \"TEMPLATE\": \"topic-{{functionality}}\"\
    ,\n        \"REGEX\": \"topic-(.*)\"\n      }\n    },\n    \"PRODUCER\": {\n \
    \     \"EVENT\": {\n        \"config\": {\n          \"options\": {\n        \
    \    \"messageCharset\": \"utf8\"\n          },\n          \"rdkafkaConf\": {\n\
    \            \"metadata.broker.list\": \"kafka:9092\",\n            \"client.id\"\
    : \"es-prod-event\",\n            \"event_cb\": true,\n            \"dr_cb\":\
    \ true,\n            \"socket.keepalive.enable\": true,\n            \"queue.buffering.max.messages\"\
    : 10000000\n          },\n          \"topicConf\": {\n            \"request.required.acks\"\
    : \"all\"\n          }\n        }\n      }\n    }\n  }\n}\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: quoting-service
  name: quoting-service-sidecar
