apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: quoting-service
  name: quoting-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: quoting-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quoting-service
    spec:
      containers:
        - env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FILTER
            - name: CSL_LOG_TRANSPORT
              value: file
            - name: EVENT_SDK_LOG_FILTER
              value: audit:*, log:warn, log:error
            - name: EVENT_SDK_LOG_METADATA_ONLY
              value: 'false'
            - name: EVENT_SDK_SIDECAR_DISABLED
              value: 'false'
            - name: EVENT_SDK_SERVER_HOST
              value: localhost
            - name: EVENT_SDK_SERVER_PORT
              value: '50051'
            - name: EVENT_SDK_VENDOR_PREFIX
              value: mojaloop
            - name: EVENT_SDK_TRACESTATE_HEADER_ENABLED
              value: 'true'
            - name: EVENT_SDK_ASYNC_OVERRIDE_EVENTS
              value: log,trace
            - name: EVENT_SDK_TRACEID_PER_VENDOR
              value: 'false'
          image: mojaloop/quoting-service:v9.3.2-snapshot
          imagePullPolicy: Always
          name: quoting-service
          ports:
            - containerPort: 3002
              name: http-api
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/quoting-service/config
              name: quoting-service-config-volume
        - command:
            - npm
            - run
            - start
          env:
            - name: LOG_LEVEL
              value: info
          image: mojaloop/event-sidecar:v9.3.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4001
              scheme: HTTP
            initialDelaySeconds: 90
          name: quoting-service-sidecar
          ports:
            - containerPort: 4001
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4001
              scheme: HTTP
            initialDelaySeconds: 120
          volumeMounts:
            - mountPath: /opt/event-sidecar/config
              name: quoting-service-sidecar-volume
      initContainers:
        - command:
            - sh
            - -c
            - until result=$(mysql -h mysql -P 3306 -u central_ledger
              --password=oyMxgZChuu  central_ledger -ss -N -e 'select is_locked from
              migration_lock;') && eval 'echo is_locked=$result' && if [ -z $result
              ]; then false; fi && if [ $result -ne 0 ]; then false; fi; do echo waiting
              for MySQL; sleep 2; done;
          image: mysql:latest
          imagePullPolicy: Always
          name: wait-for-mysql
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: default.json
                path: default.json
              - key: rules.json
                path: rules.json
            name: quoting-service-config
          name: quoting-service-config-volume
        - configMap:
            defaultMode: 420
            items:
              - key: default.json
                path: default.json
            name: quoting-service-sidecar
          name: quoting-service-sidecar-volume
