apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: quoting-service
  name: quoting-service
spec:
  ports:
    - name: http-api
      port: 80
      protocol: TCP
      targetPort: 3002
  selector:
    app.kubernetes.io/name: quoting-service
