apiVersion: v1
kind: Service
metadata:
  name: quoting-service
  labels:
    app.kubernetes.io/name: quoting-service
spec:
  ports:
  - port: 80
    targetPort: 3002
  selector:
    app.kubernetes.io/name: quoting-service
