resources:
- ./als
- ./central
- ../portal
- ../quoting-service

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: quoting-service
    spec:
      template:
        spec:
          containers:
          - name: quoting-service
            env:
            - name: QUOTE_DATABASE__HOST
              valueFrom:
                configMapKeyRef:
                  name: centralledger-mysql
                  key: MYSQL_SERVICE
            - name: QUOTE_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: centralledger-mysql
                  key: MYSQL_PASSWORD
            - name: QUOTE_DATABASE__USER
              valueFrom:
                configMapKeyRef:
                  name: centralledger-mysql
                  key: MYSQL_USER
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: portal-backend
    spec:
      template:
        spec:
          containers:
          - name: app
            env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: centralledger-mysql
                  key: MYSQL_SERVICE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: centralledger-mysql
                  key: MYSQL_PASSWORD
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: centralledger-mysql
                  key: MYSQL_USER
