resources:
  - ../../account-lookup-service
  - ./mysql

configMapGenerator:
  - name: mysql
    behavior: merge
    literals:
      - MYSQL_DATABASE=account_lookup
      - MYSQL_USER=account_lookup

secretGenerator:
  - name: mysql
    behavior: merge
    literals:
      - MYSQL_PASSWORD=oyMxgZChuu
      - MYSQL_ROOT_PASSWORD=2dMJTrx8y9
      - XTRABACKUP_PASSWORD=4WHuZ4xTLq

patches:
  - target:
      kind: Deployment
      name: account-lookup-service-admin
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        template:
          spec:
            initContainers:
              - name: run-migration
                env:
                  - name: ALS_DATABASE__SCHEMA
                    valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_DATABASE
                  - name: ALS_DATABASE__USER
                    valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_USER
                  - name: ALS_DATABASE__HOST
                    valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_SERVICE
                  - name: ALS_DATABASE__PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: mysql
                        key: MYSQL_PASSWORD
  - target:
      kind: Deployment
      name: account-lookup-.*
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        template:
          spec:
            containers:
              - name: service
                env:
                  - name: ALS_DATABASE__SCHEMA
                    valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_DATABASE
                  - name: ALS_DATABASE__USER
                    valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_USER
                  - name: ALS_DATABASE__HOST
                    valueFrom:
                      configMapKeyRef:
                        name: mysql
                        key: MYSQL_SERVICE
                  - name: ALS_DATABASE__PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: mysql
                        key: MYSQL_PASSWORD
            initContainers:
              - name: wait-for-mysql
                envFrom:
                  - configMapRef:
                      name: mysql
                  - secretRef:
                      name: mysql
