# Note that all references to mysql here are to `als-mysql`. Hypothetically, kustomize should allow
# us to use just `mysql`. However, it looks like these names are resolved globally, rather than
# hierarchically, which means we must use `als-mysql` instead of `mysql`. Which means whenever we
# rename our ALS mysql instance, we must replace all instances of `als-mysql` with the new name.
resources:
- ../../account-lookup-service
- ./mysql

configMapGenerator:
- name: als-mysql
  behavior: merge
  literals:
  - MYSQL_DATABASE=account_lookup
  - MYSQL_USER=account_lookup

secretGenerator:
- name: als-mysql
  behavior: merge
  literals:
  - MYSQL_PASSWORD=oyMxgZChuu
  - MYSQL_ROOT_PASSWORD=2dMJTrx8y9
  - XTRABACKUP_PASSWORD=4WHuZ4xTLq

patches:
- target:
    kind: Deployment
    name: account-lookup-service-admin
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored
    spec:
      template:
        spec:
          initContainers:
          - name: run-migration
            env:
            - name: ALS_DATABASE__SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: als-mysql
                  key: MYSQL_DATABASE
            - name: ALS_DATABASE__USER
              valueFrom:
                configMapKeyRef:
                  name: als-mysql
                  key: MYSQL_USER
            - name: ALS_DATABASE__HOST
              valueFrom:
                configMapKeyRef:
                  name: als-mysql
                  key: MYSQL_SERVICE
            - name: ALS_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: als-mysql
                  key: MYSQL_PASSWORD
- target:
    kind: Deployment
    name: account-lookup-.*
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored
    spec:
      template:
        spec:
          containers:
          - name: service
            env:
            - name: ALS_DATABASE__SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: als-mysql
                  key: MYSQL_DATABASE
            - name: ALS_DATABASE__USER
              valueFrom:
                configMapKeyRef:
                  name: als-mysql
                  key: MYSQL_USER
            - name: ALS_DATABASE__HOST
              valueFrom:
                configMapKeyRef:
                  name: als-mysql
                  key: MYSQL_SERVICE
            - name: ALS_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: als-mysql
                  key: MYSQL_PASSWORD
          initContainers:
          - name: wait-for-mysql
            envFrom:
            - configMapRef:
                name: als-mysql
            - secretRef:
                name: als-mysql
