nameSuffix: -timeout

patches:
  # Override the container command
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/command
        value:
          - node
          - src/handlers/index.js
          - handler
          - --timeout
    target:
      name: centralledger-handler
      kind: Deployment

resources:
  - ../base/sidecar
