resources:
- ../base

nameSuffix: -handler-settlementwindow

commonLabels:
  app.kubernetes.io/name: centralsettlement-handler-settlementwindow

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: centralsettlement
    spec:
      template:
        spec:
          containers:
          - name: app
            command: [node, src/handlers/index.js, h, --settlementwindow]
