nameSuffix: -transfer-get

patchesStrategicMerge:
  - |-
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: centralledger-handler
    spec:
      template:
        spec:
          containers:
            - name: handler
              command:
                - node
                - src/handlers/index.js
                - handler
                - --get
              env:
                - name: CLEDG_HOSTNAME
                  value: central-ledger-transfer-get.local
                - name: CLEDG_INSTRUMENTATION__METRICS__config__defaultLabels__serviceName
                  value: central-handler-get

resources:
  - ../base/handler
