apiVersion: v1
kind: Service
metadata:
  name: ml-api-adapter-service
  labels:
    app.kubernetes.io/name: ml-api-adapter-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: ml-api-adapter-service
