apiVersion: apps/v1
kind: Deployment
metadata:
  name: centralsettlement
  labels:
    app.kubernetes.io/name: centralledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: centralsettlement
  template:
    metadata:
      labels:
        app.kubernetes.io/name: centralsettlement
    spec:
      containers:
      - name: app
        command: [node, src/api/index.js]
        image: mojaloop/centralsettlement:v12.0.3
        ports:
        - containerPort: 3007
        env:
        - name: LOG_LEVEL
          value: info
        - name: CSL_LOG_TRANSPORT
          value: console
        - name: CSET_DATABASE__SCHEMA
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: MYSQL_DATABASE
        - name: CSET_DATABASE__USER
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: MYSQL_USER
        - name: CSET_DATABASE__HOST
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: MYSQL_SERVICE
        - name: CSET_DATABASE__PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: MYSQL_PASSWORD
        readinessProbe:
          httpGet:
            path: /v2/health
            port: 3007
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /v2/health
            port: 3007
            scheme: HTTP
