apiVersion: v1
kind: Service
metadata:
  name: centralsettlement
  labels:
    app.kubernetes.io/name: centralsettlement
spec:
  ports:
  - port: 80
    targetPort: 3007
  selector:
    app.kubernetes.io/name: centralsettlement
