apiVersion: v1
kind: PersistentVolume
metadata:
  name: centralledger-mysql
  labels:
    app.kubernetes.io/name: centralledger-mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: centralledger-mysql
  labels:
    # insert any desired labels to identify your claim
    app.kubernetes.io/name: centralledger-mysql
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 5Gi
