# Add:
# Sidecar
# Configmap
# Volume (from configMap)
# Volume mount
# Sidecar env var ES_INSTRUMENTATION__METRICS__config__defaultLabels__serviceName=$(NAME)

resources:
  - ../handler

# TODO: is it possible to incorporate this in the patchesStrategicMerge? If so, this entire overlay
# could be just a patch.
configMapGenerator:
  - name: event-sidecar-config
    files:
      - ./default.json

patchesStrategicMerge:
  # Add EVENT_SDK environment variables to handler container
  - |-
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: centralledger-handler
    spec:
      template:
        spec:
          containers:
            - name: centralledger-handler
              env:
                - name: EVENT_SDK_LOG_METADATA_ONLY
                  value: "false"
                - name: EVENT_SDK_SIDECAR_DISABLED
                  value: "false"
                - name: EVENT_SDK_SERVER_HOST
                  value: localhost
                - name: EVENT_SDK_SERVER_PORT
                  value: "50051"
            - command:
                - npm
                - run
                - start
              env:
                - name: LOG_LEVEL
                  value: info
                - name: LOG_FILTER
                  value: error, warn, info
                - name: EVENT_SDK_LOG_FILTER
                  value: audit:*, log:info, log:warn, log:error
                - name: EVENT_SDK_LOG_METADATA_ONLY
                  value: "true"
                - name: ES_INSTRUMENTATION__METRICS__config__defaultLabels__serviceName
                  value: $(NAME) # TODO: not actually used in event sidecar AFAICT
              image: mojaloop/event-sidecar:v9.3.0
              imagePullPolicy: Always
              livenessProbe:
                httpGet:
                  path: /health
                  port: 4001
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 15
              name: event-sidecar
              ports:
                - containerPort: 4001
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health
                  port: 4001
                  scheme: HTTP
                initialDelaySeconds: 120
                periodSeconds: 15
              volumeMounts:
                - mountPath: /opt/event-sidecar/config
                  name: sidecar-volume
          volumes:
            - name: sidecar-volume
              configMap:
                name: event-sidecar-config
                items:
                  - key: default.json
                    path: default.json
