apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: account-lookup-service
  name: account-lookup-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: account-lookup-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-lookup-service
    spec:
      containers:
        - command:
            - node
            - src/index.js
            - server
            - --api
          env:
            - name: LOG_LEVEL
              value: info
            - name: CSL_LOG_TRANSPORT
              value: console
            - name: EVENT_SDK_SIDECAR_DISABLED
              value: 'true'
            - name: ALS_INSTRUMENTATION__METRICS__config__defaultLabels__serviceName
              value: account-lookup-service
            - name: ALS_SWITCH_ENDPOINT
              value: centralledger
          image: mojaloop/account-lookup-service:v9.4.4
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: http-api
              scheme: HTTP
          name: service
          ports:
            - containerPort: 4002
              name: http-api
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http-api
              scheme: HTTP
      initContainers:
        - command:
            - sh
            - -c
            - until mysql -h als-mysql -P 3306 -u $(MYSQL_USER) --password=$(MYSQL_PASSWORD) $(MYSQL_DATABASE)   -e
              'select * from oracleEndpoint;' ; do echo waiting for MySQL; sleep 2;
              done;
          image: mysql:latest
          imagePullPolicy: Always
          name: wait-for-mysql
          envFrom:
            - secretRef:
                name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: account-lookup-service-admin
  name: account-lookup-service-admin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: account-lookup-service-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-lookup-service-admin
    spec:
      containers:
        - command:
            - node
            - src/index.js
            - server
            - --admin
          env:
            - name: LOG_LEVEL
              value: info
            - name: CSL_LOG_TRANSPORT
              value: file
            - name: EVENT_SDK_LOG_FILTER
            - name: EVENT_SDK_LOG_METADATA_ONLY
            - name: EVENT_SDK_SIDECAR_DISABLED
              value: 'true'
            - name: EVENT_SDK_SERVER_HOST
              value: localhost
            - name: EVENT_SDK_SERVER_PORT
              value: '50051'
            - name: EVENT_SDK_VENDOR_PREFIX
            - name: EVENT_SDK_TRACESTATE_HEADER_ENABLED
            - name: EVENT_SDK_ASYNC_OVERRIDE_EVENTS
            - name: EVENT_SDK_TRACEID_PER_VENDOR
            - name: ALS_INSTRUMENTATION__METRICS__config__defaultLabels__serviceName
              value: account-lookup-service-admin
          image: mojaloop/account-lookup-service:v9.4.4
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: http-admin
              scheme: HTTP
          name: service
          ports:
            - containerPort: 4001
              name: http-admin
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http-admin
              scheme: HTTP
      initContainers:
        - command:
            - sh
            - -c
            - until mysql -h als-mysql -P 3306 -u account_lookup --password=$(MYSQL_PASSWORD)  account_lookup   -e
              'select version()' ; do echo waiting for MySQL; sleep 2; done;
          image: mysql:latest
          imagePullPolicy: Always
          name: wait-for-mysql
          envFrom:
            - secretRef:
                name: mysql
        - command:
            - sh
            - -c
            - npm run migrate
          image: mojaloop/account-lookup-service:v9.4.4
          imagePullPolicy: Always
          name: run-migration
