apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: account-lookup-service
  name: account-lookup-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: account-lookup-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-lookup-service
    spec:
      containers:
        - command:
            - node
            - src/index.js
            - server
            - --api
          env:
            - name: LOG_LEVEL
              value: info
            - name: CSL_LOG_TRANSPORT
              value: file
            - name: EVENT_SDK_LOG_FILTER
            - name: EVENT_SDK_LOG_METADATA_ONLY
            - name: EVENT_SDK_SIDECAR_DISABLED
              value: 'false'
            - name: EVENT_SDK_SERVER_HOST
              value: localhost
            - name: EVENT_SDK_SERVER_PORT
              value: '50051'
            - name: EVENT_SDK_VENDOR_PREFIX
            - name: EVENT_SDK_TRACESTATE_HEADER_ENABLED
            - name: EVENT_SDK_ASYNC_OVERRIDE_EVENTS
            - name: EVENT_SDK_TRACEID_PER_VENDOR
          image: mojaloop/account-lookup-service:v9.4.4
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: http-api
              scheme: HTTP
          name: service
          ports:
            - containerPort: 4002
              name: http-api
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http-api
              scheme: HTTP
          volumeMounts:
            - mountPath: /opt/account-lookup-service/config
              name: account-lookup-service-config-volume
        - command:
            - npm
            - run
            - start
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FILTER
              value: error, warn, info
            - name: EVENT_SDK_LOG_FILTER
              value: audit:*, log:info, log:warn, log:error
            - name: EVENT_SDK_LOG_METADATA_ONLY
              value: 'true'
          image: mojaloop/event-sidecar:v9.3.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 4003
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          name: account-lookup-service-sidecar
          ports:
            - containerPort: 4003
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 4003
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - mountPath: /opt/event-sidecar/config
              name: account-lookup-service-sidecar-volume
      initContainers:
        - command:
            - sh
            - -c
            - until mysql -h als-mysql -P 3306 -u account_lookup --password=$(MYSQL_PASSWORD) account_lookup   -e
              'select * from oracleEndpoint;' ; do echo waiting for MySQL; sleep 2;
              done;
          image: mysql:latest
          imagePullPolicy: Always
          name: wait-for-mysql
          envFrom:
            - secretRef:
                name: mysql
      volumes:
        - configMap:
            items:
              - key: default.json
                path: default.json
              - key: knexfile.js
                path: knexfile.js
            name: account-lookup-service-config
          name: account-lookup-service-config-volume
        - configMap:
            items:
              - key: default.json
                path: default.json
            name: account-lookup-service-sidecar
          name: account-lookup-service-sidecar-volume
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: account-lookup-service-admin
  name: account-lookup-service-admin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: account-lookup-service-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-lookup-service-admin
    spec:
      containers:
        - command:
            - node
            - src/index.js
            - server
            - --admin
          env:
            - name: LOG_LEVEL
              value: info
            - name: CSL_LOG_TRANSPORT
              value: file
            - name: EVENT_SDK_LOG_FILTER
            - name: EVENT_SDK_LOG_METADATA_ONLY
            - name: EVENT_SDK_SIDECAR_DISABLED
              value: 'false'
            - name: EVENT_SDK_SERVER_HOST
              value: localhost
            - name: EVENT_SDK_SERVER_PORT
              value: '50051'
            - name: EVENT_SDK_VENDOR_PREFIX
            - name: EVENT_SDK_TRACESTATE_HEADER_ENABLED
            - name: EVENT_SDK_ASYNC_OVERRIDE_EVENTS
            - name: EVENT_SDK_TRACEID_PER_VENDOR
          image: mojaloop/account-lookup-service:v9.4.4
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: http-admin
              scheme: HTTP
          name: service
          ports:
            - containerPort: 4001
              name: http-admin
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http-admin
              scheme: HTTP
          volumeMounts:
            - mountPath: /opt/account-lookup-service/config
              name: account-lookup-service-admin-config-volume
        - command:
            - npm
            - run
            - start
          env:
            - name: LOG_LEVEL
              value: info
            - name: LOG_FILTER
              value: error, warn, info
            - name: EVENT_SDK_LOG_FILTER
              value: audit:*, log:info, log:warn, log:error
            - name: EVENT_SDK_LOG_METADATA_ONLY
              value: 'true'
          image: mojaloop/event-sidecar:v9.3.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 4003
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          name: event-sidecar
          ports:
            - containerPort: 4003
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 4003
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - mountPath: /opt/event-sidecar/config
              name: event-sidecar-volume
      initContainers:
        - command:
            - sh
            - -c
            - until mysql -h als-mysql -P 3306 -u account_lookup --password=$(MYSQL_PASSWORD)  account_lookup   -e
              'select version()' ; do echo waiting for MySQL; sleep 2; done;
          image: mysql:latest
          imagePullPolicy: Always
          name: wait-for-mysql
          envFrom:
            - secretRef:
                name: mysql
        - command:
            - sh
            - -c
            - npm run migrate
          image: mojaloop/account-lookup-service:v9.4.4
          imagePullPolicy: Always
          name: run-migration
          volumeMounts:
            - mountPath: /opt/account-lookup-service/config
              name: account-lookup-service-admin-config-volume
      volumes:
        - configMap:
            items:
              - key: default.json
                path: default.json
              - key: knexfile.js
                path: knexfile.js
            name: account-lookup-service-admin-config
          name: account-lookup-service-admin-config-volume
        - configMap:
            items:
              - key: default.json
                path: default.json
            name: account-lookup-service-admin-sidecar
          name: event-sidecar-volume
