apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: account-lookup-service
  name: test-account-lookup-service
spec:
  ports:
    - name: http-api
      port: 80
      protocol: TCP
      targetPort: http-api
  selector:
    app.kubernetes.io/name: account-lookup-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: account-lookup-service-admin
  name: test-account-lookup-service-admin
spec:
  ports:
    - name: http-admin
      port: 80
      protocol: TCP
      targetPort: http-admin
  selector:
    app.kubernetes.io/name: account-lookup-service-admin
