resources:
- service
- handler-settlementwindow

# The empty configmapgenerator here combined with the patch below to take env from this configmap
# lets a consumer of this base easily override env vars by defining their own configmapgenerator
# with the same name and specifying `behavior: merge`.
configMapGenerator:
- name: centralsettlement

patchesJson6902:
- target:
    kind: Deployment
    name: centralsettlement.*
  patch: |-
    - path: /spec/template/spec/containers/0/envFrom/-
      op: add
      value:
        configMapRef:
          name: centralsettlement
