resources:
- service
- handler-settlementwindow

# The empty configmapgenerator here combined with the patch below to take env from this configmap
# lets a consumer of this base easily override env vars by defining their own configmapgenerator
# with the same name and specifying `behavior: merge`.
configMapGenerator:
- name: centralsettlement

patches:
- target:
    kind: Deployment
    name: centralsettlement.*
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ignored-by-kustomize
    spec:
      template:
        spec:
          containers:
          - name: centralsettlement-service
            envFrom:
            - configMapRef:
                name: centralsettlement
