# Note that all references to mysql here are to `centralledger-mysql`. Hypothetically, kustomize
# should allow us to use just `mysql` as when this kustomization is being built the mysql
# dependency is the only possible name for `mysql`.. However, it looks like these names are
# resolved globally, rather than hierarchically, which means we must use `centralledger-mysql`
# instead of `mysql`. Which means whenever we rename our centralledger mysql instance, we must
# replace all instances of `centralledger-mysql` with the new name.
commonLabels:
  app.kubernetes.io/part-of: mojaloop
resources:
# TODO: consider attempting to replace kafka with Redpanda
- ../../kafka
- ./centralledger-mysql
- ../../centralledger
- ../../centralsettlement
- ../../ml-api-adapter

configMapGenerator:
- name: centralledger-mysql
  behavior: merge
  literals:
  - MYSQL_DATABASE=central_ledger
  - MYSQL_USER=central_ledger
- name: centralsettlement
  behavior: merge
  literals:
  # TODO: parametrise kafka host + port
  - CSET_KAFKA__CONSUMER__SETTLEMENTWINDOW__CLOSE__config__rdkafkaConf__metadata.broker.list=kafka:9092
  - CSET_KAFKA__CONSUMER__NOTIFICATION__EVENT__config__rdkafkaConf__metadata.broker.list=kafka:9092
  - CSET_KAFKA__PRODUCER__SETTLEMENTWINDOW__CLOSE__config__rdkafkaConf__metadata.broker.list=kafka:9092
  - CSET_KAFKA__PRODUCER__NOTIFICATION__EVENT__config__rdkafkaConf__metadata.broker.list=kafka:9092
- name: ml-api-adapter-service
  behavior: merge
  literals: &ml_api_adapter_service_kafka_config
  - MLAPI_KAFKA__CONSUMER__NOTIFICATION__EVENT__config__rdkafkaConf__metadata.broker.list=kafka:9092
  - MLAPI_KAFKA__PRODUCER__TRANSFER__PREPARE__config__rdkafkaConf__metadata.broker.list=kafka:9092
  - MLAPI_KAFKA__PRODUCER__TRANSFER__FULFIL__config__rdkafkaConf__metadata.broker.list=kafka:9092
  - MLAPI_KAFKA__PRODUCER__TRANSFER__GET__config__rdkafkaConf__metadata.broker.list=kafka:9092
- name: ml-api-adapter-notification-handler
  behavior: merge
  literals: *ml_api_adapter_service_kafka_config

secretGenerator:
- name: centralledger-mysql
  behavior: merge
  literals:
  - MYSQL_PASSWORD=oyMxgZChuu
  - MYSQL_ROOT_PASSWORD=2dMJTrx8y9

patches:
- target:
    kind: Deployment
    name: centralsettlement.*
  path: wait-for-mysql.patch.yaml
- target:
    kind: Deployment
    name: centralledger-handler-.*
  path: wait-for-mysql.patch.yaml
