apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignored-by-kustomize
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-mysql
        command:
        - sh
        - -c
        - until result=$(mysql -h "$MYSQL_SERVICE" -P 3306 -u "$MYSQL_USER"
          --password="$MYSQL_PASSWORD"  "$MYSQL_DATABASE" -ss -N -e 'select is_locked from
          migration_lock;') && eval 'echo is_locked=$result' && if [ -z $result
          ]; then false; fi && if [ $result -ne 0 ]; then false; fi; do echo waiting
          for MySQL; sleep 2; done;
        image: mysql:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: centralledger-mysql
        - secretRef:
            name: centralledger-mysql
      - name: wait-for-kafka
        command:
        - sh
        - -c
        # TODO: parametrise the Kafka service and port
        - until ./bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092;
          do
            echo waiting for Kafka;
            sleep 2;
          done;
        image: solsson/kafka:latest
        imagePullPolicy: Always
