name: "Smoke test manifests"
on:
  pull_request:
  push:
jobs:
  validate_manifests:
    runs-on: ubuntu-latest
    steps:

    # Setup
    - uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz

    - name: Install dependencies in environment
      run: nix-env -if default.nix

    # Tests
    - name: Smoke test parent chart
      run: kustomize build base/mojaloop | kubeval --strict

  deploy:
    needs: validate_manifests
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:

    # Env setup
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz

    - name: Install dependencies in environment
      run: nix-env -if default.nix
    - name: Checkout repository
      uses: actions/checkout@v2

    # Cluster setup
    - name: Start cluster
      run: minikube start --kubernetes-version=v1.20.2

    - name: Deploy
      run: skaffold run
