name: "Smoke test Kustomizations"
on:
  pull_request:
  push:
jobs:
  strategy:
    # It doesn't make sense to attempt a deployment if our manifests don't validate
    max-parallel: 1
  validate_manifests:
    runs-on: ubuntu-latest
    steps:

    # Setup
    - uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz

    - name: Install dependencies in environment
      run: nix-env -if default.nix

    # Tests
    - name: Smoke test parent chart
      run: kustomize build base/mojaloop | kubeval --strict

  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:

    # Env setup
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz

    - name: Install dependencies in environment
      run: nix-env -if default.nix
    - name: Checkout repository
      uses: actions/checkout@v2

    # Cluster setup
    - name: Start cluster
      run: |-
        k3d cluster create \
          --kubeconfig-update-default \
          --kubeconfig-switch-context \
          --image=rancher/k3s:v1.20.5-k3s1 \
          int-test

    - name: Deploy
      run: skaffold run
