namePrefix: als-

resources:
  - ../../mysql

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mysql
    spec:
      template:
        spec:
          containers:
            - name: database
              env:
                - name: MYSQL_DATABASE
                  value: account_lookup
                - name: MYSQL_USER
                  value: account_lookup
