apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centralledger-service
  labels:
    app.kubernetes.io/name: centralledger-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: centralledger-service
  # TODO: is progressDeadlineSeconds: 600 default?
  template:
    metadata:
      labels:
        app.kubernetes.io/name: centralledger-service
    spec:
      containers:
      - command:
        - node
        - src/api/index.js
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_FILTER
          value: error, warn, info
        - name: CSL_LOG_TRANSPORT
          value: file
        - name: EVENT_SDK_LOG_FILTER
          value: audit:*, log:warn, log:error
        - name: EVENT_SDK_LOG_METADATA_ONLY
          value: "false"
        - name: EVENT_SDK_VENDOR_PREFIX
          value: mojaloop
        - name: EVENT_SDK_TRACESTATE_HEADER_ENABLED
          value: "true"
        - name: EVENT_SDK_ASYNC_OVERRIDE_EVENTS
          value: log,trace
        - name: EVENT_SDK_TRACEID_PER_VENDOR
          value: "false"
        image: mojaloop/central-ledger:v9.5.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
        name: centralledger-service
        ports:
        - containerPort: 3001
          name: http-api
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
        - mountPath: /opt/central-ledger/config
          name: centralledger-service-config-volume
      initContainers:
      - command:
        - sh
        - -c
        - until mysql -h mysql -P 3306 -u central_ledger --password=oyMxgZChuu  central_ledger   -e
          'select version()' ; do echo waiting for MySQL; sleep 2; done;
        image: mysql:latest
        imagePullPolicy: Always
        name: wait-for-mysql
      - command:
        - sh
        - -c
        - npm run migrate
        env:
        - name: CLEDG_MIGRATIONS__RUN_DATA_MIGRATIONS
          value: "true"
        image: mojaloop/central-ledger:v9.5.0
        imagePullPolicy: Always
        name: run-migration
        volumeMounts:
        - mountPath: /opt/central-ledger/config
          name: centralledger-service-config-volume
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: default.json
            path: default.json
          - key: knexfile.js
            path: knexfile.js
          name: centralledger-service-config
        name: centralledger-service-config-volume
