resources:
  - deployments.yaml
  - services.yaml
  - ./mysql
  - ./handlers/admin-transfer
  - ./handlers/timeout
  - ./handlers/transfer-fulfil
  - ./handlers/transfer-get
  - ./handlers/transfer-position
  - ./handlers/transfer-prepare

configMapGenerator:
  - name: centralledger-service-config
    files:
      - ./configs/knexfile.js
      - default.json=./configs/centralledger-service-config.json
